name: Auto File Update

on:
  workflow_dispatch:  # This enables manual triggering

jobs:
  update-file:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Make file updates
        run: echo "Auto-updating file" >> updated_file.txt

      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add updated_file.txt
          git commit -m "Automated file update"

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
