name: Update File with API Data

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight

jobs:
  update-file:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get data from API and modify file
      run: |
        curl -s https://api.coindesk.com/v1/bpi/currentprice.json | jq '.bpi.USD.rate' > bitcoin-price.txt

    - name: Commit changes
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add bitcoin-price.txt
        git commit -m "Updated bitcoin price at $(date)"

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
