name: Auto Update HTML File Every Minute

on:
  schedule:
    # Run every minute
    - cron: '* * * * *'

jobs:
  update-html:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Append a letter to the HTML file
      - name: Append letter to HTML file
        run: |
          FILE="index.html"  # Replace with your HTML file name
          
          # Check if the HTML file exists
          if [ -f "$FILE" ]; then
            # Read the last character and determine the next letter
            LAST_LETTER=$(tail -c 1 "$FILE")
            echo "Last letter in the file: '$LAST_LETTER'"
            
            if [[ -z "$LAST_LETTER" ]]; then
              # If the file is empty, start with 'A'
              NEXT_LETTER="A"
            else
              # Calculate the next letter (assuming uppercase letters only)
              if [[ "$LAST_LETTER" == "Z" ]]; then
                echo "Reached 'Z', resetting to 'A'."
                NEXT_LETTER="A"  # Reset to 'A' after 'Z'
              else
                NEXT_LETTER=$(printf "\\$(printf '%03o' "$(( $(printf '%d' "'$LAST_LETTER") + 1 ))")")
              fi
            fi
            
            # Append the next letter to the HTML file
            echo "$NEXT_LETTER" >> "$FILE"
            echo "Appended letter '$NEXT_LETTER' to $FILE"
          else
            echo "File $FILE does not exist."
            exit 1  # Exit with error if file does not exist
          fi

      # Step 3: Commit changes if the file was updated
      - name: Commit changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add index.html  # Replace with your HTML file name
          
          # Check if there are changes to commit
          if ! git diff-index --quiet HEAD --; then
            git commit -m "Automated update: Added letter '$NEXT_LETTER' at $(date +'%Y-%m-%d %H:%M:%S')"
            git push
          else
            echo "No changes to commit."
          fi
